Loaded module: cuda/12.1
Loaded module: cudnn/v8.9.1.23-prod-cuda-12.X
[NbConvertApp] Converting notebook Detection_dataset_preparation.ipynb to notebook
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
  File "/zhome/18/7/137746/miniconda3/envs/msc/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/jupyter_core/application.py", line 280, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 412, in start
    self.convert_notebooks()
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 590, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 556, in convert_single_notebook
    output, resources = self.export_single_notebook(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 479, in export_single_notebook
    output, resources = self.exporter.from_filename(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 203, in from_filename
    return self.from_file(f, resources=resources, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 222, in from_file
    return self.from_notebook_node(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/exporters/notebook.py", line 36, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 156, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 354, in _preprocess
    nbc, resc = preprocessor(nbc, resc)  # type:ignore[operator]
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/preprocessors/base.py", line 48, in __call__
    return self.preprocess(nb, resources)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/preprocessors/execute.py", line 102, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/preprocessors/execute.py", line 123, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/asyncio/base_events.py", line 1884, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Task exception was never retrieved
future: <Task finished name='Task-41' coro=<NotebookClient.async_execute_cell() done, defined at /zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbclient/client.py:916> exception=CellExecutionError('An error occurred while executing the following cell:\n------------------\n#datasets = [(\'TruthfulQA\', TruthfulQA_df), (\'Politicians\', politicians_df)]\ndatasets = [(ds_file_name.replace(\'_prepared.csv\', \'\'), pd.read_csv(os.path.join(data_dir, ds_file_name))) for ds_file_name in filter(lambda x: \'.csv\' in x, os.listdir(data_dir))]\nmodels = ["facebook/opt-125m", "facebook/opt-350m", "facebook/opt-1.3b", "facebook/opt-2.7b", "meta-llama/Llama-2-7b-chat-hf", "meta-llama/Llama-2-13b-chat-hf", "meta-llama/Llama-2-70b-chat-hf", "microsoft/Phi-3-mini-4k-instruct", "meta-llama/Meta-Llama-3-8B", "meta-llama/Meta-Llama-3-70B-Instruct"]\nmodel_setup_fns = [opt_setup_fn, opt_setup_fn, opt_setup_fn, opt_setup_fn, None, None, None, None, None, None]\n\nfor model, model_setup_fn in tqdm(list(zip(models, model_setup_fns)), leave=False, desc="Models"):\n  # Remember model setup function!\n  ## For opt: Set model.model.layers = model.model.decoder.layers\n  compute_activations_on_datasets(model, datasets, model_setup_fn=model_setup_fn)\n------------------\n\n----- stderr -----\n\nKeyboardInterrupt\n------------------\n\n\n')>
Traceback (most recent call last):
  File "/zhome/18/7/137746/miniconda3/envs/msc/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/jupyter_core/application.py", line 280, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 412, in start
    self.convert_notebooks()
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 590, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 556, in convert_single_notebook
    output, resources = self.export_single_notebook(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/nbconvertapp.py", line 479, in export_single_notebook
    output, resources = self.exporter.from_filename(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 203, in from_filename
    return self.from_file(f, resources=resources, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 222, in from_file
    return self.from_notebook_node(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/exporters/notebook.py", line 36, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 156, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/exporters/exporter.py", line 354, in _preprocess
    nbc, resc = preprocessor(nbc, resc)  # type:ignore[operator]
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/preprocessors/base.py", line 48, in __call__
    return self.preprocess(nb, resources)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/preprocessors/execute.py", line 102, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbconvert/preprocessors/execute.py", line 123, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/asyncio/base_events.py", line 1884, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/zhome/18/7/137746/miniconda3/envs/msc/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#datasets = [('TruthfulQA', TruthfulQA_df), ('Politicians', politicians_df)]
datasets = [(ds_file_name.replace('_prepared.csv', ''), pd.read_csv(os.path.join(data_dir, ds_file_name))) for ds_file_name in filter(lambda x: '.csv' in x, os.listdir(data_dir))]
models = ["facebook/opt-125m", "facebook/opt-350m", "facebook/opt-1.3b", "facebook/opt-2.7b", "meta-llama/Llama-2-7b-chat-hf", "meta-llama/Llama-2-13b-chat-hf", "meta-llama/Llama-2-70b-chat-hf", "microsoft/Phi-3-mini-4k-instruct", "meta-llama/Meta-Llama-3-8B", "meta-llama/Meta-Llama-3-70B-Instruct"]
model_setup_fns = [opt_setup_fn, opt_setup_fn, opt_setup_fn, opt_setup_fn, None, None, None, None, None, None]

for model, model_setup_fn in tqdm(list(zip(models, model_setup_fns)), leave=False, desc="Models"):
  # Remember model setup function!
  ## For opt: Set model.model.layers = model.model.decoder.layers
  compute_activations_on_datasets(model, datasets, model_setup_fn=model_setup_fn)
------------------

----- stderr -----

KeyboardInterrupt
------------------



